In [1]:
import os
import numpy as np
import pandas as pd
import statsmodels.formula.api as sm

### Linear Regression

In [2]:
df_merged = pd.read_csv('/Users/amit/Coding/Projects/TeslaStock/Regression/final_df.csv', parse_dates=['date'])
df_merged

,date,open,close,change,percent_change,market_cap,tweet_count,number_articles,daily_sentiment_score,day_week
0,2020-12-01,597.59,584.76,NaN,NaN,23614.2,30745,2,-0.10000,Tuesday
1,2020-12-02,556.44,568.82,-15.94,-0.0273,27175.8,25388,1,-0.08000,Wednesday
2,2020-12-03,590.02,593.38,24.56,0.0432,25249.5,29679,2,0.09500,Thursday
3,2020-12-04,591.01,599.04,5.66,0.0095,17612.6,23875,0,0.00000,Friday
4,2020-12-07,604.92,641.76,42.72,0.0713,36137.3,26011,1,-0.20000,Monday
5,2020-12-08,625.51,649.88,8.12,0.0127,41764.5,37171,5,0.03200,Tuesday
6,2020-12-09,653.69,604.48,-45.40,-0.0699,43094.1,38379,1,0.10000,Wednesday
7,2020-12-10,574.37,627.07,22.59,0.0374,42065.9,41190,0,0.00000,Thursday
8,2020-12-11,615.01,609.99,-17.08,-0.0272,28349.3,34966,0,0.00000,Friday
9,2020-12-14,619.00,639.83,29.84,0.0489,33297.1,34028,0,0.17000,Monday
10,2020-12-15,643.28,633.25,-6.58,-0.0103,28637.8,32445,1,0.00000,Tuesday
11,2020-12-16,628.23,622.77,-10.48,-0.0165,26216.0,48276,0,0.00000,Wednesday
12,2020-12-17,628.19,655.90,33.13,0.0532,36907.6,41236,1,0.11000,Thursday
13,2020-12-18,668.90,695.00,39.10,0.0596,154377.7,39760,4,0.07250,Friday
14,2020-12-21,666.24,649.86,-45.14,-0.0649,37721.3,52425,2,0.00000,Monday
15,2020-12-22,648.00,640.34,-9.52,-0.0146,33115.8,50127,8,-0.01375,Tuesday
16,2020-12-23,632.20,645.98,5.64,0.0088,21429.1,48469,0,0.00000,Wednesday

In [3]:
df_merged = df_merged.filter(['date', 'percent_change', 'tweet_count', 'number_articles', 'daily_sentiment_score'], axis=1)
df_merged = df_merged.drop(0, axis=0)
df_merged = df_merged.set_index('date')
df_merged

,percent_change,tweet_count,number_articles,daily_sentiment_score
date,,,,
2020-12-02,-0.0273,25388,1,-0.08000
2020-12-03,0.0432,29679,2,0.09500
2020-12-04,0.0095,23875,0,0.00000
2020-12-07,0.0713,26011,1,-0.20000
2020-12-08,0.0127,37171,5,0.03200
2020-12-09,-0.0699,38379,1,0.10000
2020-12-10,0.0374,41190,0,0.00000
2020-12-11,-0.0272,34966,0,0.00000
2020-12-14,0.0489,34028,0,0.17000
2020-12-15,-0.0103,32445,1,0.00000
2020-12-16,-0.0165,48276,0,0.00000
2020-12-17,0.0532,41236,1,0.11000
2020-12-18,0.0596,39760,4,0.07250
2020-12-21,-0.0649,52425,2,0.00000
2020-12-22,-0.0146,50127,8,-0.01375
2020-12-23,0.0088,48469,0,0.00000

In [4]:
df_merged.corr()

,percent_change,tweet_count,number_articles,daily_sentiment_score
percent_change,1.000000,-0.318720,-0.018179,0.038297
tweet_count,-0.318720,1.000000,0.305838,0.204922
number_articles,-0.018179,0.305838,1.000000,-0.001520
daily_sentiment_score,0.038297,0.204922,-0.001520,1.000000

In [5]:
# Linear Regression Model
result = sm.ols(formula="percent_change ~ number_articles + daily_sentiment_score + tweet_count", data=df_merged).fit()

In [6]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         percent_change   R-squared:                       0.121
Model:                            OLS   Adj. R-squared:                 -0.099
Method:                 Least Squares   F-statistic:                    0.5508
Date:                Fri, 25 Dec 2020   Prob (F-statistic):              0.657
Time:                        10:02:31   Log-Likelihood:                 29.167
No. Observations:                  16   AIC:                            -50.33
Df Residuals:                      12   BIC:                            -47.24
Df Model:                           3
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.0700      0.051      1.368      0.196      -0.041       0.181
number_articles           0.0018      0.005      0.335      0.743      -0.010       0.014
daily_sentiment_score     0.0582      0.141      0.413      0.687      -0.249       0.365
tweet_count           -1.773e-06   1.39e-06     -1.276      0.226    -4.8e-06    1.25e-06
==============================================================================
Omnibus:                        0.853   Durbin-Watson:                   2.546
Prob(Omnibus):                  0.653   Jarque-Bera (JB):                0.757
Skew:                          -0.270   Prob(JB):                        0.685
Kurtosis:                       2.081   Cond. No.                     4.84e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.84e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/stats/stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

### Linear Regression Using Absolute Value

In [7]:
# Use abs value of percent_change and daily_sentiment_score
df_merged2 = df_merged.copy()
df_merged2['percent_change'] = abs(df_merged2['percent_change'])
df_merged2['daily_sentiment_score'] = abs(df_merged2['daily_sentiment_score'])
df_merged2

,percent_change,tweet_count,number_articles,daily_sentiment_score
date,,,,
2020-12-02,0.0273,25388,1,0.08000
2020-12-03,0.0432,29679,2,0.09500
2020-12-04,0.0095,23875,0,0.00000
2020-12-07,0.0713,26011,1,0.20000
2020-12-08,0.0127,37171,5,0.03200
2020-12-09,0.0699,38379,1,0.10000
2020-12-10,0.0374,41190,0,0.00000
2020-12-11,0.0272,34966,0,0.00000
2020-12-14,0.0489,34028,0,0.17000
2020-12-15,0.0103,32445,1,0.00000
2020-12-16,0.0165,48276,0,0.00000
2020-12-17,0.0532,41236,1,0.11000
2020-12-18,0.0596,39760,4,0.07250
2020-12-21,0.0649,52425,2,0.00000
2020-12-22,0.0146,50127,8,0.01375
2020-12-23,0.0088,48469,0,0.00000

In [8]:
df_merged2.corr()

,percent_change,tweet_count,number_articles,daily_sentiment_score
percent_change,1.000000,-0.024091,-0.087631,0.669286
tweet_count,-0.024091,1.000000,0.305838,-0.443837
number_articles,-0.087631,0.305838,1.000000,-0.080538
daily_sentiment_score,0.669286,-0.443837,-0.080538,1.000000

In [9]:
# Linear Regression Model Using Absolute Value
result_abs = sm.ols(formula="percent_change ~ number_articles + daily_sentiment_score + tweet_count", data=df_merged2).fit()

In [10]:
print(result_abs.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         percent_change   R-squared:                       0.558
Model:                            OLS   Adj. R-squared:                  0.448
Method:                 Least Squares   F-statistic:                     5.054
Date:                Fri, 25 Dec 2020   Prob (F-statistic):             0.0172
Time:                        10:02:39   Log-Likelihood:                 44.699
No. Observations:                  16   AIC:                            -81.40
Df Residuals:                      12   BIC:                            -78.31
Df Model:                           3
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                -0.0147      0.023     -0.630      0.540      -0.066       0.036
number_articles          -0.0014      0.002     -0.689      0.504      -0.006       0.003
daily_sentiment_score     0.2895      0.075      3.867      0.002       0.126       0.453
tweet_count            9.861e-07   5.73e-07      1.721      0.111   -2.62e-07    2.23e-06
==============================================================================
Omnibus:                        0.484   Durbin-Watson:                   1.483
Prob(Omnibus):                  0.785   Jarque-Bera (JB):                0.553
Skew:                           0.319   Prob(JB):                        0.759
Kurtosis:                       2.350   Cond. No.                     6.90e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.9e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy/stats/stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "