In [9]:
import numpy as np
import pandas as pd
import yfinance as yf

In [10]:
tsla = yf.Ticker("TSLA")
tsla.info

{'zip': '94304',
 'sector': 'Consumer Cyclical',
 'fullTimeEmployees': 48016,
 'longBusinessSummary': 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, Netherlands, Norway, and internationally. The company operates in two segments, Automotive; and Energy Generation and Storage. The Automotive segment offers sedans and sport utility vehicles. It also provides electric powertrain components and systems; and services for electric vehicles through its company-owned service locations, and Tesla mobile service technicians, as well as sells used vehicles. This segment markets and sells its products through a network of company-owned stores and galleries, as well as through its own Website. The Energy Generation and Storage segment offers energy storage products, such as rechargeable lithium-ion battery systems for use in homes, industrial, commercial facilities, and utility grids; and designs, manufactures, installs, maintains, leases, and sells solar energy generation and energy storage products to residential and commercial customers. It also provides vehicle insurance services, as well as renewable energy. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was founded in 2003 and is headquartered in Palo Alto, California.',
 'city': 'Palo Alto',
 'phone': '650-681-5000',
 'state': 'CA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.tesla.com',
 'maxAge': 1,
 'address1': '3500 Deer Creek Road',
 'industry': 'Auto Manufacturers',
 'previousClose': 567.6,
 'regularMarketOpen': 597.59,
 'twoHundredDayAverage': 345.48404,
 'trailingAnnualDividendYield': None,
 'payoutRatio': 0,
 'volume24Hr': None,
 'regularMarketDayHigh': 597.85,
 'navPrice': None,
 'averageDailyVolume10Day': 48917783,
 'totalAssets': None,
 'regularMarketPreviousClose': 567.6,
 'fiftyDayAverage': 453.29114,
 'trailingAnnualDividendRate': None,
 'open': 597.59,
 'toCurrency': None,
 'averageVolume10days': 48917783,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': 1.966741,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 572.05,
 'priceHint': 2,
 'currency': 'USD',
 'trailingPE': 1118.088,
 'regularMarketVolume': 38689894,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 554294575104,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 52426563,
 'priceToSalesTrailing12Months': 19.672579,
 'dayLow': 572.05,
 'ask': 572,
 'ytdReturn': None,
 'askSize': 800,
 'volume': 38689894,
 'fiftyTwoWeekHigh': 607.8,
 'forwardPE': 149.93846,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 65.45,
 'bid': 568,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 800,
 'dayHigh': 597.85,
 'exchange': 'NMS',
 'shortName': 'Tesla, Inc.',
 'longName': 'Tesla, Inc.',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-18000000',
 'quoteType': 'EQUITY',
 'symbol': 'TSLA',
 'messageBoardId': 'finmb_27444752',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 19.747,
 'beta3Year': None,
 'profitMargins': 0.01973,
 'enterpriseToEbitda': 138.441,
 '52WeekChange': 7.7793894,
 'morningStarRiskRating': None,
 'forwardEps': 3.9,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 947900992,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'bookValue': 16.91,
 'sharesShort': 47898025,
 'sharesPercentSharesOut': 0.0505,
 'fundFamily': None,
 'lastFiscalYearEnd': 1577750400,
 'heldPercentInstitutions': 0.42479,
 'netIncomeToCommon': 533000000,
 'trailingEps': 0.523,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.17659247,
 'priceToBook': 34.580723,
 'heldPercentInsiders': 0.2002,
 'nextFiscalYearEnd': 1640908800,
 'mostRecentQuarter': 1601424000,
 'shortRatio': 1.57,
 'sharesShortPreviousMonthDate': 1602720000,
 'floatShares': 759524420,
 'enterpriseValue': 556395462656,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1598832000,
 'lastSplitFactor': '5:1',
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 1.315,
 'dateShortInterest': 1605225600,
 'pegRatio': 0.73,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.063,
 'sharesShortPriorMonth': 52955116,
 'category': None,
 'fiveYearAverageReturn': None,
 'regularMarketPrice': 597.59,
 'logo_url': 'https://logo.clearbit.com/tesla.com'}

In [26]:
hist = tsla.history(start="2019-01-01", end="2020-12-01")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2019-01-02,61.220001,63.026001,59.759998,62.023998,58293000,0,0.0
2019-01-03,61.400002,61.880001,59.476002,60.071999,34826000,0,0.0
2019-01-04,61.200001,63.599998,60.546001,63.537998,36970500,0,0.0
2019-01-07,64.344002,67.348000,63.549999,66.991997,37756000,0,0.0
2019-01-08,68.391998,68.802002,65.403999,67.070000,35042500,0,0.0
...,...,...,...,...,...,...,...
2020-11-23,503.500000,526.000000,501.790009,521.849976,50260300,0,0.0
2020-11-24,540.400024,559.989990,526.200012,555.380005,53648500,0,0.0
2020-11-25,550.059998,574.000000,545.369995,574.000000,48930200,0,0.0
2020-11-27,581.159973,598.780029,578.450012,585.760010,37561100,0,0.0
2020-11-30,602.210022,607.799988,554.510010,567.599976,63003100,0,0.0

In [52]:
df_tsla = hist
df_tsla = df_tsla.reset_index()
df_tsla.columns = df_tsla.columns.str.replace(' ', '').str.lower()
df_tsla = df_tsla.rename(columns={'stocksplits':'stock_splits'})
df_tsla['change'] = df_tsla['close']-df_tsla['close'].shift(1)
df_tsla['percent_change'] = (df_tsla['close']/df_tsla['close'].shift(1))-1
df_tsla['market_cap'] = df_tsla['close']*df_tsla['volume']/1000000
df_tsla[['open','high','low','close','change']] = df_tsla[['open','high','low','close','change']].round(2)
df_tsla[['percent_change']] = df_tsla[['percent_change']].round(4)
df_tsla[['market_cap']] = df_tsla[['market_cap']].round(1)
#df_tsla = df_tsla[['date','open','high','low','close','change','percent_change','volume','market_cap','stock_splits']]
df_tsla

,date,open,high,low,close,volume,dividends,stock_splits,change,percent_change,market_cap
0,2019-01-02,61.22,63.03,59.76,62.02,58293000,0,0.0,NaN,NaN,3615.6
1,2019-01-03,61.40,61.88,59.48,60.07,34826000,0,0.0,-1.95,-0.0315,2092.1
2,2019-01-04,61.20,63.60,60.55,63.54,36970500,0,0.0,3.47,0.0577,2349.0
3,2019-01-07,64.34,67.35,63.55,66.99,37756000,0,0.0,3.45,0.0544,2529.3
4,2019-01-08,68.39,68.80,65.40,67.07,35042500,0,0.0,0.08,0.0012,2350.3
...,...,...,...,...,...,...,...,...,...,...,...
478,2020-11-23,503.50,526.00,501.79,521.85,50260300,0,0.0,32.24,0.0658,26228.3
479,2020-11-24,540.40,559.99,526.20,555.38,53648500,0,0.0,33.53,0.0643,29795.3
480,2020-11-25,550.06,574.00,545.37,574.00,48930200,0,0.0,18.62,0.0335,28085.9
481,2020-11-27,581.16,598.78,578.45,585.76,37561100,0,0.0,11.76,0.0205,22001.8
482,2020-11-30,602.21,607.80,554.51,567.60,63003100,0,0.0,-18.16,-0.0310,35760.6